#! /bin/bash

# display a csv file with proper columns

if [[ -z $(which column) ]]; then
  echo "column tool not found, please install 'bsdmainutils' using 'apt' or 'dnf' installer"
  exit
fi
if [[ -z $1 ]]; then
  echo "Please enter a CSV file on the command line"
  exit
fi
perl -pe 's/((?<=,)|(?<=^)),/ ,/g;' "$@" | column -t -s, | exec less  -F -S -X -K

