package archivedb

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// fixture copies testdata/archives.json (generated by Python's
// json.dump(indent=4)) into a temp dir and returns its path.
func fixture(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile("testdata/archives.json")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "froster-archives.json")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

const (
	modernKey    = "/home/dp/temp/froster.data.RCv"
	recursiveKey = "/data/proj/alpha"
	legacyKey    = "/archive/old/stuff"
	futureKey    = "/home/dp/unicode-éè/däta \U0001F600"
)

func TestLoadMissingFileIsEmpty(t *testing.T) {
	db, err := Load(filepath.Join(t.TempDir(), "nope.json"))
	if err != nil {
		t.Fatalf("Load of missing file: %v", err)
	}
	if db.Len() != 0 {
		t.Fatalf("expected empty DB, got %d entries", db.Len())
	}
	if db.Get("/anything") != nil {
		t.Fatal("Get on empty DB should return nil")
	}
}

func TestLoadFixture(t *testing.T) {
	db, err := Load(fixture(t))
	if err != nil {
		t.Fatal(err)
	}
	if db.Len() != 4 {
		t.Fatalf("want 4 entries, got %d", db.Len())
	}

	e := db.Get(modernKey)
	if e == nil {
		t.Fatal("modern entry not found")
	}
	if e.ArchiveFolder != ":s3:froster-dipeit/froster/home/dp/temp/froster.data.RCv" {
		t.Errorf("archive_folder = %q", e.ArchiveFolder)
	}
	if e.Provider != "AWS" || e.Endpoint != "https://s3.us-west-2.amazonaws.com" {
		t.Errorf("provider/endpoint = %q/%q", e.Provider, e.Endpoint)
	}
	if e.ArchiveMode != ModeSingle || e.IsRecursive() {
		t.Errorf("archive_mode = %q", e.ArchiveMode)
	}
	if !e.IsGlacier() {
		t.Error("DEEP_ARCHIVE should be glacier")
	}

	leg := db.Get(legacyKey)
	if leg == nil {
		t.Fatal("legacy entry not found")
	}
	if leg.Provider != "" || leg.Endpoint != "" {
		t.Error("legacy entry should have empty provider/endpoint")
	}
	if leg.NIHProjectURL != "https://reporter.nih.gov/project-details/9331239" ||
		leg.NIHProjectPI != "MOLLER, DAVID ROBERT" {
		t.Errorf("legacy NIH keys: %q / %q", leg.NIHProjectURL, leg.NIHProjectPI)
	}

	fut := db.Get(futureKey)
	if fut == nil {
		t.Fatal("unicode/future entry not found")
	}
	if got := string(fut.Extra("future_count")); got != "42" {
		t.Errorf("future_count raw = %q", got)
	}
	if fut.Extra("nonexistent") != nil {
		t.Error("Extra of absent key should be nil")
	}
}

// TestRoundTripByteIdentical verifies that rewriting a Python-authored file
// without changes reproduces it byte for byte (unknown keys, key order,
// indentation, ensure_ascii escapes).
func TestRoundTripByteIdentical(t *testing.T) {
	path := fixture(t)
	orig, _ := os.ReadFile(path)

	db, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	// A no-op upsert of an existing entry triggers a full rewrite.
	if err := db.Upsert(db.Get(modernKey)); err != nil {
		t.Fatal(err)
	}

	got, _ := os.ReadFile(path)
	if string(got) != string(orig) {
		t.Errorf("rewrite is not byte-identical to Python output\n--- python ---\n%s\n--- go ---\n%s", orig, got)
	}
}

// TestFreshWriteMatchesPython verifies that a database created from scratch
// in Go is byte-identical to Python json.dump(indent=4) of the same data.
func TestFreshWriteMatchesPython(t *testing.T) {
	golden, err := os.ReadFile("testdata/golden_fresh.json")
	if err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(t.TempDir(), "froster-archives.json")
	db, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	err = db.Upsert(&Entry{
		LocalFolder:      modernKey,
		ArchiveFolder:    ":s3:froster-dipeit/froster" + modernKey,
		S3StorageClass:   "DEEP_ARCHIVE",
		Profile:          "froster2",
		Provider:         "AWS",
		Endpoint:         "https://s3.us-west-2.amazonaws.com",
		ArchiveMode:      ModeSingle,
		Timestamp:        "2025-10-16T19:51:57.936903",
		TimestampArchive: "2025-10-16T19:51:57.936903",
		User:             "dp",
	})
	if err != nil {
		t.Fatal(err)
	}

	got, _ := os.ReadFile(path)
	if string(got) != string(golden) {
		t.Errorf("fresh Go write differs from Python golden\n--- python ---\n%s\n--- go ---\n%s", golden, got)
	}
}

// TestPythonCanReadGoOutput shells out to python3 (if available) and
// checks that the Go-written file parses and re-dumps unchanged.
func TestPythonCanReadGoOutput(t *testing.T) {
	if _, err := exec.LookPath("python3"); err != nil {
		t.Skip("python3 not available")
	}
	path := fixture(t)
	db, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.MarkDeleted(modernKey, time.Date(2026, 7, 10, 12, 0, 0, 123456000, time.UTC)); err != nil {
		t.Fatal(err)
	}
	script := `
import json, sys
with open(sys.argv[1]) as f:
    raw = f.read()
data = json.loads(raw)
assert data[sys.argv[2]]["timestamp_deleted"] == "2026-07-10T12:00:00.123456", data[sys.argv[2]]
assert json.dumps(data, indent=4) == raw, "python re-dump differs from go output"
print("OK")
`
	out, err := exec.Command("python3", "-c", script, path, modernKey).CombinedOutput()
	if err != nil || !strings.Contains(string(out), "OK") {
		t.Fatalf("python3 validation failed: %v\n%s", err, out)
	}
}

func TestGetRecursiveParentLookup(t *testing.T) {
	db, err := Load(fixture(t))
	if err != nil {
		t.Fatal(err)
	}

	// Subfolder of a Recursive entry resolves to the parent entry.
	if e := db.Get("/data/proj/alpha/sub1/sub2"); e == nil || e.LocalFolder != recursiveKey {
		t.Errorf("subfolder of recursive entry: got %+v", e)
	}
	// Subfolder of a Single entry does not.
	if e := db.Get(modernKey + "/sub"); e != nil {
		t.Errorf("subfolder of Single entry should not match, got %q", e.LocalFolder)
	}
	// Unrelated path.
	if e := db.Get("/data/other"); e != nil {
		t.Errorf("unrelated path should not match, got %q", e.LocalFolder)
	}
	// Exact match still wins for the recursive root itself.
	if e := db.Get(recursiveKey); e == nil || e.ArchiveMode != ModeRecursive {
		t.Error("exact match on recursive root failed")
	}
}

func TestAllSortedByTimestampDesc(t *testing.T) {
	db, err := Load(fixture(t))
	if err != nil {
		t.Fatal(err)
	}
	all := db.All()
	if len(all) != 4 {
		t.Fatalf("want 4, got %d", len(all))
	}
	for i := 1; i < len(all); i++ {
		if all[i-1].Timestamp < all[i].Timestamp {
			t.Errorf("All() not sorted desc at %d: %q < %q", i, all[i-1].Timestamp, all[i].Timestamp)
		}
	}
	if all[0].LocalFolder != futureKey { // 2026 timestamp is newest
		t.Errorf("newest first: got %q", all[0].LocalFolder)
	}
}

func TestEntriesUnder(t *testing.T) {
	db, err := Load(fixture(t))
	if err != nil {
		t.Fatal(err)
	}
	under := db.EntriesUnder("/data")
	if len(under) != 1 || under[0].LocalFolder != recursiveKey {
		t.Errorf("EntriesUnder(/data) = %v", under)
	}
	// Prefix match must be path-segment aware: /data/proj must not match
	// a hypothetical /data/project2.
	if got := db.EntriesUnder("/data/pro"); len(got) != 0 {
		t.Errorf("EntriesUnder(/data/pro) should be empty, got %d", len(got))
	}
	if got := db.EntriesUnder("/data/proj/alpha/"); len(got) != 1 {
		t.Errorf("trailing slash parent should still match, got %d", len(got))
	}
	if got := db.EntriesUnder("/"); len(got) != db.Len() {
		t.Errorf("EntriesUnder(/) should return everything, got %d", len(got))
	}
}

func TestMarkDeletedAndRestored(t *testing.T) {
	path := fixture(t)
	db, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	when := time.Date(2026, 7, 10, 9, 30, 15, 0, time.UTC) // zero microseconds
	if err := db.MarkDeleted(legacyKey, when); err != nil {
		t.Fatal(err)
	}
	if err := db.MarkRestored(legacyKey, when.Add(42*time.Microsecond)); err != nil {
		t.Fatal(err)
	}

	re, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	e := re.Get(legacyKey)
	if e.TimestampDeleted != "2026-07-10T09:30:15" {
		t.Errorf("timestamp_deleted = %q (zero microseconds must omit fraction, like Python isoformat)", e.TimestampDeleted)
	}
	if e.TimestampRestored != "2026-07-10T09:30:15.000042" {
		t.Errorf("timestamp_restored = %q", e.TimestampRestored)
	}

	// New keys must be appended at the end of the entry, matching Python
	// dict-insertion order.
	raw, _ := os.ReadFile(path)
	iDel := strings.Index(string(raw), `"timestamp_deleted"`)
	iRes := strings.Index(string(raw), `"timestamp_restored"`)
	iPI := strings.Index(string(raw), `"nih_project_pi"`)
	if !(iPI < iDel && iDel < iRes) {
		t.Errorf("stamp keys not appended in order: pi=%d deleted=%d restored=%d", iPI, iDel, iRes)
	}

	// MarkDeleted on an unknown folder errors.
	if err := db.MarkDeleted("/no/such/folder", when); err == nil {
		t.Error("MarkDeleted of unknown folder should fail")
	}

	// Stamping a subfolder of a Recursive entry stamps the parent entry
	// (Get semantics).
	if err := db.MarkRestored(recursiveKey+"/sub", when); err != nil {
		t.Fatal(err)
	}
	re2, _ := Load(path)
	if re2.Get(recursiveKey).TimestampRestored == "" {
		t.Error("recursive parent should have been stamped")
	}
}

func TestUpsertReplacesWholesale(t *testing.T) {
	path := fixture(t)
	db, _ := Load(path)

	// Mirrors Python data[key] = value: replacing an entry drops any keys
	// the caller did not carry over (tier change re-upserts the loaded
	// entry, so unknown keys ride along when going through Get).
	e := db.Get(futureKey)
	e.S3StorageClass = "GLACIER" // tier change
	if err := db.Upsert(e); err != nil {
		t.Fatal(err)
	}
	re, _ := Load(path)
	got := re.Get(futureKey)
	if got.S3StorageClass != "GLACIER" {
		t.Errorf("s3_storage_class = %q", got.S3StorageClass)
	}
	if string(got.Extra("future_meta")) == "" {
		t.Error("unknown keys must survive a Get-then-Upsert cycle")
	}

	// Trailing separators are stripped from the key like Python's
	// folder.rstrip(os.path.sep).
	if err := db.Upsert(&Entry{LocalFolder: "/new/folder///", Timestamp: "2026-01-01T00:00:00"}); err != nil {
		t.Fatal(err)
	}
	re, _ = Load(path)
	if re.Get("/new/folder") == nil {
		t.Error("key should be rstripped of path separators")
	}

	if err := db.Upsert(&Entry{LocalFolder: "///"}); err == nil {
		t.Error("entry whose key normalizes to empty must be rejected")
	}
	if err := db.Upsert(nil); err == nil {
		t.Error("nil entry must be rejected")
	}
}

func TestSetExtraRoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.json")
	db, _ := Load(path)
	e := &Entry{LocalFolder: "/x", Timestamp: "2026-01-01T00:00:00"}
	if err := e.SetExtra("custom_key", json.RawMessage(`{"a": [1, 2]}`)); err != nil {
		t.Fatal(err)
	}
	if err := e.SetExtra("local_folder", json.RawMessage(`"boom"`)); err == nil {
		t.Error("SetExtra must reject known keys")
	}
	if err := db.Upsert(e); err != nil {
		t.Fatal(err)
	}
	re, _ := Load(path)
	// The raw bytes carry the on-disk (Python-style indented) formatting
	// after a round trip; compare semantically.
	var compact bytes.Buffer
	if err := json.Compact(&compact, re.Get("/x").Extra("custom_key")); err != nil {
		t.Fatal(err)
	}
	if compact.String() != `{"a":[1,2]}` {
		t.Errorf("custom_key = %q", compact.String())
	}
}

func TestConcurrentWriters(t *testing.T) {
	path := filepath.Join(t.TempDir(), "froster-archives.json")
	const n = 20
	var wg sync.WaitGroup
	errs := make(chan error, n)
	for i := range n {
		wg.Add(1)
		go func() {
			defer wg.Done()
			db, err := Load(path) // one handle per goroutine
			if err != nil {
				errs <- err
				return
			}
			folder := filepath.Join("/data", "folder", string(rune('a'+i)))
			errs <- db.Upsert(&Entry{
				LocalFolder:   folder,
				ArchiveFolder: ":s3:bucket/froster" + folder,
				ArchiveMode:   ModeSingle,
				Timestamp:     FormatTimestamp(time.Now()),
			})
		}()
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			t.Fatal(err)
		}
	}

	db, err := Load(path)
	if err != nil {
		t.Fatalf("file corrupt after concurrent writes: %v", err)
	}
	if db.Len() != n {
		t.Errorf("lost updates: want %d entries, got %d", n, db.Len())
	}
}

func TestCorruptFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "froster-archives.json")
	if err := os.WriteFile(path, []byte("{ not json"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := Load(path)
	if !errors.Is(err, ErrCorrupt) {
		t.Errorf("want ErrCorrupt, got %v", err)
	}

	// A top-level array is also corrupt for our purposes.
	os.WriteFile(path, []byte("[]"), 0o644)
	if _, err := Load(path); !errors.Is(err, ErrCorrupt) {
		t.Errorf("top-level array: want ErrCorrupt, got %v", err)
	}

	// Mutating through a stale handle must refuse to clobber a corrupt
	// file (Python aborts the write too).
	good := filepath.Join(t.TempDir(), "g.json")
	db, _ := Load(good)
	os.WriteFile(good, []byte("garbage"), 0o644)
	if err := db.Upsert(&Entry{LocalFolder: "/x"}); !errors.Is(err, ErrCorrupt) {
		t.Errorf("mutate over corrupt file: want ErrCorrupt, got %v", err)
	}
	if raw, _ := os.ReadFile(good); string(raw) != "garbage" {
		t.Error("corrupt file must not be overwritten")
	}
}

func TestPermissionsPreserved(t *testing.T) {
	path := fixture(t)
	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatal(err)
	}
	db, _ := Load(path)
	if err := db.MarkDeleted(modernKey, time.Now()); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Errorf("permissions not preserved: %v", info.Mode().Perm())
	}
}

func TestFormatTimestamp(t *testing.T) {
	cases := []struct {
		t    time.Time
		want string
	}{
		{time.Date(2025, 1, 2, 3, 4, 5, 0, time.UTC), "2025-01-02T03:04:05"},
		{time.Date(2025, 1, 2, 3, 4, 5, 60000, time.UTC), "2025-01-02T03:04:05.000060"},
		{time.Date(2025, 10, 16, 19, 51, 57, 936903000, time.UTC), "2025-10-16T19:51:57.936903"},
	}
	for _, c := range cases {
		if got := FormatTimestamp(c.t); got != c.want {
			t.Errorf("FormatTimestamp(%v) = %q, want %q", c.t, got, c.want)
		}
	}
}

func TestParseRemote(t *testing.T) {
	r, err := ParseRemote(":s3:froster-dipeit/froster/home/dp/temp/froster.data.RCv")
	if err != nil {
		t.Fatal(err)
	}
	if r.Bucket != "froster-dipeit" || r.Prefix != "froster/home/dp/temp/froster.data.RCv" {
		t.Errorf("parsed %+v", r)
	}
	if r.String() != ":s3:froster-dipeit/froster/home/dp/temp/froster.data.RCv" {
		t.Errorf("String() = %q", r.String())
	}
	if _, err := ParseRemote(":s3:bucketonly"); err == nil {
		t.Error("remote without '/' must fail to parse (Python raises on unpack)")
	}
}

func TestBucketInfo(t *testing.T) {
	e := &Entry{
		LocalFolder:    "/home/dp/temp/froster.data.RCv",
		ArchiveFolder:  ":s3:froster-dipeit/froster/home/dp/temp/froster.data.RCv",
		S3StorageClass: "DEEP_ARCHIVE",
		Profile:        "froster2",
		ArchiveMode:    ModeRecursive,
		User:           "dp",
	}

	// The folder itself.
	bi, err := e.BucketInfo(e.LocalFolder)
	if err != nil {
		t.Fatal(err)
	}
	if bi.Bucket != "froster-dipeit" {
		t.Errorf("bucket = %q", bi.Bucket)
	}
	if bi.Prefix != "froster/home/dp/temp/froster.data.RCv/" {
		t.Errorf("prefix = %q", bi.Prefix)
	}
	if !bi.Recursive || !bi.Glacier || bi.Profile != "froster2" || bi.User != "dp" {
		t.Errorf("flags: %+v", bi)
	}

	// A subfolder of a stored parent (Python: prefix.replace(local_folder,
	// '') + folder + '/').
	bi, err = e.BucketInfo(e.LocalFolder + "/sub")
	if err != nil {
		t.Fatal(err)
	}
	if bi.Prefix != "froster/home/dp/temp/froster.data.RCv/sub/" {
		t.Errorf("subfolder prefix = %q", bi.Prefix)
	}
}

// TestEnsureASCIIEscaping checks that non-ASCII content written by Go uses
// the same \uXXXX escapes as Python (ensure_ascii=True), including
// surrogate pairs and the DEL character.
func TestEnsureASCIIEscaping(t *testing.T) {
	path := filepath.Join(t.TempDir(), "a.json")
	db, _ := Load(path)
	if err := db.Upsert(&Entry{
		LocalFolder: "/x",
		User:        "\u00e9 \U0001F600 <&> \u007f \t \u0001",
		Timestamp:   "2026-01-01T00:00:00",
	}); err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(path)
	// Python: json.dumps("\u00e9 \U0001F600 <&> \u007f \t \u0001") ->
	// "\\u00e9 \\ud83d\\ude00 <&> \\u007f \\t \\u0001"
	want := `"\u00e9 \ud83d\ude00 <&> \u007f \t \u0001"`
	if !strings.Contains(string(raw), want) {
		t.Errorf("escaping mismatch, want %s in:\n%s", want, raw)
	}
}
