name: Install Froster locally
run-name: Froster local install on Ubuntu-latest.
on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      LOCAL_INSTALL: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipx
      run: python -m pip install pipx

    - name: Install froster locally
      run: ./install.sh

    - name: Source ~/.bashrc
      run: source ~/.bashrc

    - name: Check Froster is installed
      run: froster --info

